### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by aashutoshrathi** [cerebro-iiitv/web-2018#19]
OAuth is throwing an error:

![image](https://user-images.githubusercontent.com/21199234/36673878-53ad3e96-1b2a-11e8-8f6b-48d68bc1adc1.png)

```
This domain (cerebro-2018-f1052.firebaseapp.com) is not 
authorized to run this operation. Add it to the OAuth redirect 
domains list in the Firebase console -> Auth section -> Sign in method tab. 
Dismiss
```

Is it changed to the actual URL?

**Comment by singhpratyush** [comment]
@aashutoshrathi: This may be happening because you are using an older version of the app. Please try making a hard refresh.

**Comment by aashutoshrathi** [comment]
Fixed :+1:
