### ISSUE TITLE
Fix deploy in Travis

### ISSUE THREAD

**Issue by singhpratyush** [cerebro-iiitv/web-2018#2]

**Comment by simsausaurabh** [comment]
@singhpratyush a separate ```.eslintrc``` needs to be inserted since it is checking from the pre-defined lint check, and ```package.json``` needs to be updated for the same. If I'm right shall I make the changes?

Reference: https://github.com/airbnb/javascript/issues/1046

**Comment by Monal5031** [comment]
Go ahead @simsausaurabh

**Comment by singhpratyush** [comment]
Not valid now.
