### ISSUE TITLE
Bug in viewing events

### ISSUE THREAD

**Issue by Monal5031** [cerebro-iiitv/web-2018#32]
The bug here is that if I click on viewing individual events, it doesn't redirect me to the top of the Individual events rather somewhere in the middle.
cc:  @singhpratyush @anshumanv

**Comment by singhpratyush** [comment]
Requires a manual scroll to top call in `componentDidMount`.

**Comment by anshumanv** [comment]
It works but I'm not entirely satisfied with the solution, please update if found something better.
