### ISSUE TITLE
html tags need to be rendered

### ISSUE THREAD

**Issue by Monal5031** [cerebro-iiitv/web-2018#34]
![screenshot from 2018-03-02 22-56-57](https://user-images.githubusercontent.com/21009189/36913153-086f4de6-1e6f-11e8-8c1a-43a5e846d3ba.png)

`<br>` is not being rendered, also rules and description might need extra `<ul>` or `<ol>`

**Comment by anshumanv** [comment]
Nobody uses br now, what's your need?

**Comment by Monal5031** [comment]
Why do we need a `<br>`, `<ol>` or `<ul>`?

**Comment by anshumanv** [comment]
idk

**Comment by Monal5031** [comment]
We need those line breaks and list items :expressionless:

**Comment by anshumanv** [comment]
Firebase returns a string right? It'll be inserted as is

**Comment by Monal5031** [comment]
I tried using `\n`.
Try some google search to do this in react @anshumanv , maybe the solution would be to convert string to unicode.

**Comment by anshumanv** [comment]
I don't know how to do that. :worried: Let @Lucifer24 do it.

**Comment by Monal5031** [comment]
ping @aashutoshrathi I hope you'd find some solution to this.

**Comment by aashutoshrathi** [comment]
Have you tried adding `{'\n'}`.

**Comment by Monal5031** [comment]
Yes @aashutoshrathi Last time I tried `\n` didn't get rendered too.

**Comment by aashutoshrathi** [comment]
No, I mean exactly `{"\n"}` as React's TextBox treats this as newline.

**Comment by Monal5031** [comment]
No, I'll try it in a bit.

**Comment by Monal5031** [comment]
@aashutoshrathi Nope, still doesn't work

**Comment by singhpratyush** [comment]
https://stackoverflow.com/a/23663555/5628527
