### ISSUE TITLE
Inconsistent time display

### ISSUE THREAD

**Issue by Monal5031** [cerebro-iiitv/web-2018#35]
12:00 pm is displayed as `00:00 pm` which should be `12:00 noon` on eventList page.

**Comment by anshumanv** [comment]
Please give link to event page.

**Comment by Monal5031** [comment]
@anshumanv not individual event, the populated view of events. Look for Ideathon event.

**Comment by Monal5031** [comment]
ping @anshumanv this will be a small change but great deal in regard to accessibility.

**Comment by anshumanv** [comment]
Changes should be done to firebase data I think.

**Comment by Monal5031** [comment]
No, this won't be possible in firebase. Check your mobile I've sent the screenshot there.

**Comment by anshumanv** [comment]
Cool thanks @Monal5031 :smile:, looking into it. :+1:
