### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by igniteeng000** [cerebro-iiitv/web-2018#43]
Its not working.

**Comment by anshumanv** [comment]
Works, please recheck.

**Comment by igniteeng000** [comment]
I dont't find it clickable

**Comment by anshumanv** [comment]
Good for you then.

**Comment by anshumanv** [comment]
Please tell me where and on what you tested this.

**Comment by igniteeng000** [comment]
https://cerebro.iiitvadodara.ac.in/dashboard

**Comment by igniteeng000** [comment]
working on another system. Closed

**Comment by anshumanv** [comment]
> Please tell me where and on what you tested this.

By this I meant, browser, OS etc.

**Comment by igniteeng000** [comment]
Upto when register buttons will start functioning. or Team register buttons

**Comment by anshumanv** [comment]
Please use clear descriptive language for ease. :relieved:

**Comment by igniteeng000** [comment]
Team register buttons are not working?

**Comment by anshumanv** [comment]
I think for now, only leader registers the team.
@Monal5031 is it so?

**Comment by igniteeng000** [comment]
Team register buttons are working same as individual register.

**Comment by igniteeng000** [comment]
In team contest team members need to be unique or not

**Comment by igniteeng000** [comment]
if so then how will u manage redundancy
