### ISSUE TITLE
Create welcome component

### ISSUE THREAD

**Issue by anshumanv** [cerebro-iiitv/web-2018#7]
The top section of the home page, which can have some good js background (say particle/anime etc) and the logo of techfest in the centre.

**Comment by anshumanv** [comment]
Consequently, @aashutoshrathi can suggest some good background effects.

**Comment by Monal5031** [comment]
@anshumanv done?

**Comment by singhpratyush** [comment]
We can try improving the performance by decreasing the number of particles and not creating new ones on click.

I think @cyberNinja21 is looking for some alternative too. But as of now, it is implemented. I am closing this.

Please open a new issue for enhancements if any.

**Comment by anshumanv** [comment]
Welcome screen looks majestic. :heart_eyes:

**Comment by anshumanv** [comment]
@singhpratyush can you please re-deploy once?
